import pytest
import pandas as pd
import torch
from torch_geometric.data import HeteroData


@pytest.fixture
def hetero_data() -> HeteroData:
    data = HeteroData()
    data['artist'].x = torch.tensor([3, 1, 0, 2])
    data['song'].x = torch.tensor([10, 9, 11])
    data['performance'].x = torch.tensor([20, 21, 22, 24, 23])

    data['artist', 'performs', 'performance'].edge_index = torch.tensor([
        [1, 1, 3, 3, 3],  # values zero and three missing.
        [0, 1, 0, 1, 2]   # 23 and 24 missing.
    ])
    data['performance', 'performing', 'song'].edge_index = torch.tensor([
        [0, 1, 2, 4],  # 24 missing (island); 23 is not an island (but has no performs relation)
        [0, 0, 2, 2]   # song 9 is an island
    ])
    data['artist', 'composed', 'song'].edge_index = torch.tensor([
        [0, 1],  # three is not an island: only composes. zero is an island.
        [0, 2]
    ])

    data['performance'].y = torch.tensor([1, 2, 3, 4, 5]) / 10
    data['artist'].y = torch.tensor([3, 5, 4, 9], dtype=torch.float32)
    return data

@pytest.fixture
def recording_traits():
    """Sample recording traits.

    These are the subset of real data for Kind Of Blue, Giant Steps and The Shape of Jazz to Come.
    """
    traits = {
        "index": [
            159729,
            159730,
            270583,  # So What
            270585,  # Blue in Green
            323177,
            384218,
            384219,
            384220,
            384221,
            384222,
            384223,
            14535669,
            21881892,
            21881893,
            21881894,
            28147910,
            28147911,
            30646764
        ],
        "columns": [
            "discogs_id",
            "release_group_id",
            "title",
            "album",
            "artist",
            "release_date"
        ],
        "data": [
            [
                6276183,
                38581,
                "All Blues",
                "Kind of Blue",
                "Miles Davis",
                "1959-08-17"
            ],
            [
                6276183,
                38581,
                "Flamenco Sketches",
                "Kind of Blue",
                "Miles Davis",
                "1959-08-17"
            ],
            [
                6276183,
                38581,
                "So What",
                "Kind of Blue",
                "Miles Davis",
                "1959-08-17"
            ],
            [
                6276183,
                38581,
                "Blue in Green",
                "Kind of Blue",
                "Miles Davis",
                "1959-08-17"
            ],
            [
                2155244,
                57784,
                "Mr. P.C.",
                "Giant Steps",
                "John Coltrane",
                "1960-01-31"
            ],
            [
                488973,
                54091,
                "Lonely Woman",
                "The Shape of Jazz to Come",
                "Ornette Coleman",
                "1959-10-31"
            ],
            [
                488973,
                54091,
                "Eventually",
                "The Shape of Jazz to Come",
                "Ornette Coleman",
                "1959-10-31"
            ],
            [
                488973,
                54091,
                "Peace",
                "The Shape of Jazz to Come",
                "Ornette Coleman",
                "1959-10-31"
            ],
            [
                488973,
                54091,
                "Focus on Sanity",
                "The Shape of Jazz to Come",
                "Ornette Coleman",
                "1959-10-31"
            ],
            [
                488973,
                54091,
                "Congeniality",
                "The Shape of Jazz to Come",
                "Ornette Coleman",
                "1959-10-31"
            ],
            [
                488973,
                54091,
                "Chronology",
                "The Shape of Jazz to Come",
                "Ornette Coleman",
                "1959-10-31"
            ],
            [
                6276183,
                38581,
                "Freddie Freeloader",
                "Kind of Blue",
                "Miles Davis",
                "1959-08-17"
            ],
            [
                2155244,
                57784,
                "Giant Steps",
                "Giant Steps",
                "John Coltrane",
                "1960-01-31"
            ],
            [
                2155244,
                57784,
                "Cousin Mary",
                "Giant Steps",
                "John Coltrane",
                "1960-01-31"
            ],
            [
                2155244,
                57784,
                "Naima",
                "Giant Steps",
                "John Coltrane",
                "1960-01-31"
            ],
            [
                2155244,
                57784,
                "Countdown",
                "Giant Steps",
                "John Coltrane",
                "1960-01-31"
            ],
            [
                2155244,
                57784,
                "Spiral",
                "Giant Steps",
                "John Coltrane",
                "1960-01-31"
            ],
            [
                488973,
                54091,
                "The Blessing",
                "The Shape of Jazz to Come",
                "Ornette Coleman",
                "2021-08-03"
            ]
        ]
    }
    return pd.DataFrame.from_records(traits['data'], index=traits['index'], columns=traits['columns'])

@pytest.fixture
def spotify_data():
    """This is basically every other song on the relevant albums.

    These should match the data in recording traits. The are from
    someone's (my) actual spotify data dump, so represent real
    spotify data.
    """
    return [
        {
            'ts': '2026-01-19T01:08:16Z',
            'platform': 'not_applicable',
            'ms_played': 562640,
            'conn_country': 'US',
            'ip_addr': '47.216.192.110',
            'master_metadata_track_name': 'So What (feat. John Coltrane, Cannonball Adderley & Bill Evans)',
            'master_metadata_album_artist_name': 'Miles Davis',
            'master_metadata_album_album_name': 'Kind Of Blue (Legacy Edition)',
            'spotify_track_uri': 'spotify:track:4vLYewWIvqHfKtJDk8c8tq',
            'episode_name': None,
            'episode_show_name': None,
            'spotify_episode_uri': None,
            'audiobook_title': None,
            'audiobook_uri': None,
            'audiobook_chapter_uri': None,
            'audiobook_chapter_title': None,
            'reason_start': 'remote',
            'reason_end': 'trackdone',
            'shuffle': False,
            'skipped': False,
            'offline': False,
            'offline_timestamp': 1768784333,
            'incognito_mode': False},
        {
            'ts': '2026-01-19T01:23:40Z',
            'platform': 'not_applicable',
            'ms_played': 337733,
            'conn_country': 'US',
            'ip_addr': '47.216.192.110',
            'master_metadata_track_name': 'Blue in Green (feat. John Coltrane & Bill Evans)',
            'master_metadata_album_artist_name': 'Miles Davis',
            'master_metadata_album_album_name': 'Kind Of Blue (Legacy Edition)',
            'spotify_track_uri': 'spotify:track:0aWMVrwxPNYkKmFthzmpRi',
            'episode_name': None,
            'episode_show_name': None,
            'spotify_episode_uri': None,
            'audiobook_title': None,
            'audiobook_uri': None,
            'audiobook_chapter_uri': None,
            'audiobook_chapter_title': None,
            'reason_start': 'trackdone',
            'reason_end': 'trackdone',
            'shuffle': False,
            'skipped': False,
            'offline': False,
            'offline_timestamp': 1768785483,
            'incognito_mode': False},
        {
            'ts': '2026-01-19T01:44:39Z',
            'platform': 'not_applicable',
            'ms_played': 566134,
            'conn_country': 'US',
            'ip_addr': '47.216.192.110',
            'master_metadata_track_name': 'Flamenco Sketches (feat. John Coltrane, Cannonball Adderley & Bill Evans)',
            'master_metadata_album_artist_name': 'Miles Davis',
            'master_metadata_album_album_name': 'Kind Of Blue (Legacy Edition)',
            'spotify_track_uri': 'spotify:track:6dRx7OUXfvosnXG3g9lWGi',
            'episode_name': None,
            'episode_show_name': None,
            'spotify_episode_uri': None,
            'audiobook_title': None,
            'audiobook_uri': None,
            'audiobook_chapter_uri': None,
            'audiobook_chapter_title': None,
            'reason_start': 'trackdone',
            'reason_end': 'trackdone',
            'shuffle': False,
            'skipped': False,
            'offline': False,
            'offline_timestamp': 1768786513,
            'incognito_mode': False},
        {
            'ts': '2026-01-19T01:55:02Z',
            'platform': 'not_applicable',
            'ms_played': 51586,
            'conn_country': 'US',
            'ip_addr': '47.216.192.110',
            'master_metadata_track_name': 'Freddie Freeloader - Studio Sequence 1',
            'master_metadata_album_artist_name': 'Miles Davis',
            'master_metadata_album_album_name': 'Kind Of Blue (Legacy Edition)',
            'spotify_track_uri': 'spotify:track:0OYCtl0lZeteFq2sIZbCHf',
            'episode_name': None,
            'episode_show_name': None,
            'spotify_episode_uri': None,
            'audiobook_title': None,
            'audiobook_uri': None,
            'audiobook_chapter_uri': None,
            'audiobook_chapter_title': None,
            'reason_start': 'trackdone',
            'reason_end': 'trackdone',
            'shuffle': False,
            'skipped': False,
            'offline': False,
            'offline_timestamp': 1768787651,
            'incognito_mode': False},
        {
            'ts': '2026-01-19T01:57:57Z',
            'platform': 'not_applicable',
            'ms_played': 88506,
            'conn_country': 'US',
            'ip_addr': '47.216.192.110',
            'master_metadata_track_name': 'Freddie Freeloader - Studio Sequence 2',
            'master_metadata_album_artist_name': 'Miles Davis',
            'master_metadata_album_album_name': 'Kind Of Blue (Legacy Edition)',
            'spotify_track_uri': 'spotify:track:3FdeddUjZryl1JW2DbzR0x',
            'episode_name': None,
            'episode_show_name': None,
            'spotify_episode_uri': None,
            'audiobook_title': None,
            'audiobook_uri': None,
            'audiobook_chapter_uri': None,
            'audiobook_chapter_title': None,
            'reason_start': 'trackdone',
            'reason_end': 'trackdone',
            'shuffle': False,
            'skipped': False,
            'offline': False,
            'offline_timestamp': 1768787788,
            'incognito_mode': False},
        {
            'ts': '2026-01-19T02:00:03Z',
            'platform': 'not_applicable',
            'ms_played': 11653,
            'conn_country': 'US',
            'ip_addr': '47.216.192.110',
            'master_metadata_track_name': 'So What - Studio Sequence 2',
            'master_metadata_album_artist_name': 'Miles Davis',
            'master_metadata_album_album_name': 'Kind Of Blue (Legacy Edition)',
            'spotify_track_uri': 'spotify:track:7BcUaElEzhmBeeIRTN4xdW',
            'episode_name': None,
            'episode_show_name': None,
            'spotify_episode_uri': None,
            'audiobook_title': None,
            'audiobook_uri': None,
            'audiobook_chapter_uri': None,
            'audiobook_chapter_title': None,
            'reason_start': 'trackdone',
            'reason_end': 'trackdone',
            'shuffle': False,
            'skipped': False,
            'offline': False,
            'offline_timestamp': 1768787991,
            'incognito_mode': False},
        {
            'ts': '2026-01-19T02:02:42Z',
            'platform': 'not_applicable',
            'ms_played': 42320,
            'conn_country': 'US',
            'ip_addr': '47.216.192.110',
            'master_metadata_track_name': 'Flamenco Sketches - Studio Sequence 1',
            'master_metadata_album_artist_name': 'Miles Davis',
            'master_metadata_album_album_name': 'Kind Of Blue (Legacy Edition)',
            'spotify_track_uri': 'spotify:track:745roqGwMrDnjNO1S3Q5ex',
            'episode_name': None,
            'episode_show_name': None,
            'spotify_episode_uri': None,
            'audiobook_title': None,
            'audiobook_uri': None,
            'audiobook_chapter_uri': None,
            'audiobook_chapter_title': None,
            'reason_start': 'trackdone',
            'reason_end': 'trackdone',
            'shuffle': False,
            'skipped': False,
            'offline': False,
            'offline_timestamp': 1768788120,
            'incognito_mode': False},
        {
            'ts': '2026-01-19T02:04:10Z',
            'platform': 'not_applicable',
            'ms_played': 18907,
            'conn_country': 'US',
            'ip_addr': '47.216.192.110',
            'master_metadata_track_name': 'All Blues - Studio Sequence',
            'master_metadata_album_artist_name': 'Miles Davis',
            'master_metadata_album_album_name': 'Kind Of Blue (Legacy Edition)',
            'spotify_track_uri': 'spotify:track:7FA0qrw667jTZR3wNcITQE',
            'episode_name': None,
            'episode_show_name': None,
            'spotify_episode_uri': None,
            'audiobook_title': None,
            'audiobook_uri': None,
            'audiobook_chapter_uri': None,
            'audiobook_chapter_title': None,
            'reason_start': 'trackdone',
            'reason_end': 'trackdone',
            'shuffle': False,
            'skipped': False,
            'offline': False,
            'offline_timestamp': 1768788231,
            'incognito_mode': False},
        {
            'ts': '2026-01-19T02:19:49Z',
            'platform': 'not_applicable',
            'ms_played': 349053,
            'conn_country': 'US',
            'ip_addr': '47.216.192.110',
            'master_metadata_track_name': 'Fran-Dance (feat. John Coltrane, Cannonball Adderley & Bill Evans)',
            'master_metadata_album_artist_name': 'Miles Davis',
            'master_metadata_album_album_name': 'Kind Of Blue (Legacy Edition)',
            'spotify_track_uri': 'spotify:track:6YCAJqpG0uSZSwidZODdjW',
            'episode_name': None,
            'episode_show_name': None,
            'spotify_episode_uri': None,
            'audiobook_title': None,
            'audiobook_uri': None,
            'audiobook_chapter_uri': None,
            'audiobook_chapter_title': None,
            'reason_start': 'trackdone',
            'reason_end': 'trackdone',
            'shuffle': False,
            'skipped': False,
            'offline': False,
            'offline_timestamp': 1768788840,
            'incognito_mode': False},
        {
            'ts': '2026-01-19T02:41:53Z',
            'platform': 'not_applicable',
            'ms_played': 439740,
            'conn_country': 'US',
            'ip_addr': '47.216.192.110',
            'master_metadata_track_name': 'Love For Sale',
            'master_metadata_album_artist_name': 'Miles Davis',
            'master_metadata_album_album_name': 'Kind Of Blue (Legacy Edition)',
            'spotify_track_uri': 'spotify:track:66vrjgMvWOLyeKBuMGA0Cz',
            'episode_name': None,
            'episode_show_name': None,
            'spotify_episode_uri': None,
            'audiobook_title': None,
            'audiobook_uri': None,
            'audiobook_chapter_uri': None,
            'audiobook_chapter_title': None,
            'reason_start': 'trackdone',
            'reason_end': 'logout',
            'shuffle': False,
            'skipped': False,
            'offline': False,
            'offline_timestamp': 1768789473,
            'incognito_mode': False},
        {
            'ts': '2026-02-08T02:19:40Z',
            'platform': 'not_applicable',
            'ms_played': 418247,
            'conn_country': 'US',
            'ip_addr': '47.216.192.110',
            'master_metadata_track_name': 'Mr. P.C. - Mono',
            'master_metadata_album_artist_name': 'John Coltrane',
            'master_metadata_album_album_name': 'Giant Steps',
            'spotify_track_uri': 'spotify:track:1Z6Yxm3WpEJRkE0tGLr31y',
            'episode_name': None,
            'episode_show_name': None,
            'spotify_episode_uri': None,
            'audiobook_title': None,
            'audiobook_uri': None,
            'audiobook_chapter_uri': None,
            'audiobook_chapter_title': None,
            'reason_start': 'trackdone',
            'reason_end': 'trackdone',
            'shuffle': False,
            'skipped': False,
            'offline': False,
            'offline_timestamp': 1770516762,
            'incognito_mode': False},
        {
            'ts': '2026-02-10T18:11:30Z',
            'platform': 'ios',
            'ms_played': 262510,
            'conn_country': 'US',
            'ip_addr': '47.216.192.110',
            'master_metadata_track_name': 'Eventually',
            'master_metadata_album_artist_name': 'Ornette Coleman',
            'master_metadata_album_album_name': 'The Shape Of Jazz To Come',
            'spotify_track_uri': 'spotify:track:4m4CTIkJedguy5kK4tLPC0',
            'episode_name': None,
            'episode_show_name': None,
            'spotify_episode_uri': None,
            'audiobook_title': None,
            'audiobook_uri': None,
            'audiobook_chapter_uri': None,
            'audiobook_chapter_title': None,
            'reason_start': 'trackdone',
            'reason_end': 'trackdone',
            'shuffle': False,
            'skipped': False,
            'offline': False,
            'offline_timestamp': 1770746827,
            'incognito_mode': False},
        {
            'ts': '2026-02-10T18:27:27Z',
            'platform': 'ios',
            'ms_played': 410787,
            'conn_country': 'US',
            'ip_addr': '47.216.192.110',
            'master_metadata_track_name': 'Focus on Sanity',
            'master_metadata_album_artist_name': 'Ornette Coleman',
            'master_metadata_album_album_name': 'The Shape Of Jazz To Come',
            'spotify_track_uri': 'spotify:track:59OezEtep4hCy0n62Z3js5',
            'episode_name': None,
            'episode_show_name': None,
            'spotify_episode_uri': None,
            'audiobook_title': None,
            'audiobook_uri': None,
            'audiobook_chapter_uri': None,
            'audiobook_chapter_title': None,
            'reason_start': 'trackdone',
            'reason_end': 'trackdone',
            'shuffle': False,
            'skipped': False,
            'offline': False,
            'offline_timestamp': 1770747635,
            'incognito_mode': False},
        {
            'ts': '2026-02-10T18:40:18Z',
            'platform': 'ios',
            'ms_played': 363573,
            'conn_country': 'US',
            'ip_addr': '47.216.192.110',
            'master_metadata_track_name': 'Chronology',
            'master_metadata_album_artist_name': 'Ornette Coleman',
            'master_metadata_album_album_name': 'The Shape Of Jazz To Come',
            'spotify_track_uri': 'spotify:track:14FkDSrkQPko4YMhx6dLI2',
            'episode_name': None,
            'episode_show_name': None,
            'spotify_episode_uri': None,
            'audiobook_title': None,
            'audiobook_uri': None,
            'audiobook_chapter_uri': None,
            'audiobook_chapter_title': None,
            'reason_start': 'trackdone',
            'reason_end': 'trackdone',
            'shuffle': False,
            'skipped': False,
            'offline': False,
            'offline_timestamp': 1770748454,
            'incognito_mode': False},
        {
            'ts': '2026-02-14T23:14:05Z',
            'platform': 'ios',
            'ms_played': 261251,
            'conn_country': 'US',
            'ip_addr': '47.216.192.110',
            'master_metadata_track_name': 'Eventually - Mono',
            'master_metadata_album_artist_name': 'Ornette Coleman',
            'master_metadata_album_album_name': 'The Shape of Jazz To Come',
            'spotify_track_uri': 'spotify:track:78pWfqEjVfqjguvgaKgBU4',
            'episode_name': None,
            'episode_show_name': None,
            'spotify_episode_uri': None,
            'audiobook_title': None,
            'audiobook_uri': None,
            'audiobook_chapter_uri': None,
            'audiobook_chapter_title': None,
            'reason_start': 'trackdone',
            'reason_end': 'trackdone',
            'shuffle': False,
            'skipped': False,
            'offline': False,
            'offline_timestamp': 1771110583,
            'incognito_mode': False},
        {
            'ts': '2026-02-14T23:30:00Z',
            'platform': 'ios',
            'ms_played': 411288,
            'conn_country': 'US',
            'ip_addr': '47.216.192.110',
            'master_metadata_track_name': 'Focus on Sanity - Mono',
            'master_metadata_album_artist_name': 'Ornette Coleman',
            'master_metadata_album_album_name': 'The Shape of Jazz To Come',
            'spotify_track_uri': 'spotify:track:3JWyRSgP1rSiZLvSZvBY47',
            'episode_name': None,
            'episode_show_name': None,
            'spotify_episode_uri': None,
            'audiobook_title': None,
            'audiobook_uri': None,
            'audiobook_chapter_uri': None,
            'audiobook_chapter_title': None,
            'reason_start': 'trackdone',
            'reason_end': 'trackdone',
            'shuffle': False,
            'skipped': False,
            'offline': False,
            'offline_timestamp': 1771111387,
            'incognito_mode': False},
        {
            'ts': '2026-02-14T23:42:51Z',
            'platform': 'ios',
            'ms_played': 364015,
            'conn_country': 'US',
            'ip_addr': '47.216.192.110',
            'master_metadata_track_name': 'Chronology - Mono',
            'master_metadata_album_artist_name': 'Ornette Coleman',
            'master_metadata_album_album_name': 'The Shape of Jazz To Come',
            'spotify_track_uri': 'spotify:track:12tkS7o3Oa6bQEp5B6m2pr',
            'episode_name': None,
            'episode_show_name': None,
            'spotify_episode_uri': None,
            'audiobook_title': None,
            'audiobook_uri': None,
            'audiobook_chapter_uri': None,
            'audiobook_chapter_title': None,
            'reason_start': 'trackdone',
            'reason_end': 'trackdone',
            'shuffle': False,
            'skipped': False,
            'offline': False,
            'offline_timestamp': 1771112207,
            'incognito_mode': False}
    ]
